name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-close: 5
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        close-issue-message: 'This issue has been closed because it has been stale for 5 days with no activity. Feel free to reopen it if the problem still occurs.'
        close-pr-message: 'This PR has been closed because it has been stale for 5 days with no activity. Feel free to reopen it if you would like to continue the work.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'future,bug'
        exempt-pr-labels: 'future'
        remove-stale-when-updated: true
        remove-issue-stale-when-updated: true
        remove-pr-stale-when-updated: true
